import { TdsRule } from './types';

export const TDS_RULES: TdsRule[] = [
  // ===================================
  // 1. COMMISSION OR BROKERAGE
  // ===================================
  {
    id: 'r_1_i',
    category: 'Commission or Brokerage',
    description: 'Insurance commission',
    reference: '393(1) [Sl. No. 1(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 15000,
    thresholdNote: 'per financial year',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_1_ii',
    category: 'Commission or Brokerage',
    description: 'Other commission or brokerage (not insurance)',
    reference: '393(1) [Sl. No. 1(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 15000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_comm_ind',
    category: 'Commission or Brokerage',
    description: 'Commission/Brokerage (by Individual/HUF not liable for audit)',
    reference: '393(1) [Sl. No. 6(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 5000000,
    thresholdNote: 'per financial year',
    payerType: 'non-specified',
    payeeType: 'resident',
  },
  // ===================================
  // 2. RENT
  // ===================================
  {
    id: 'r_2_i',
    category: 'Rent',
    description: 'Rent (paid by Individual/HUF not liable for audit)',
    reference: '393(1) [Sl. No. 2(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per month or part of a month',
    payerType: 'non-specified',
    payeeType: 'resident',
  },
  {
    id: 'r_2_ii_a',
    category: 'Rent',
    description: 'Rent for machinery, plant, or equipment',
    reference: '393(1) [Sl. No. 2(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 240000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_2_ii_b',
    category: 'Rent',
    description: 'Rent for land, building, or furniture/fittings',
    reference: '393(1) [Sl. No. 2(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 240000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  // ===================================
  // 3. IMMOVABLE PROPERTY (Sale/Transfer)
  // ===================================
  {
    id: 'r_3_i',
    category: 'Immovable Property',
    description: 'Transfer of immovable property (Other than agricultural land)',
    reference: '393(1) [Sl. No. 3(i)]',
    rate: 1,
    rateUnit: '%',
    threshold: 5000000,
    thresholdNote: 'per transaction',
    specialNote: 'Rate is 1% of consideration or stamp duty value, whichever is higher.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_3_ii',
    category: 'Immovable Property',
    description: 'Consideration for transfer under specified agreement (Joint Development)',
    reference: '393(1) [Sl. No. 3(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_3_iii',
    category: 'Immovable Property',
    description: 'Compensation on compulsory acquisition',
    reference: '393(1) [Sl. No. 3(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 500000,
    payerType: 'all',
    payeeType: 'resident',
  },
  // ===================================
  // 4. WINNINGS
  // ===================================
  {
    id: 'r_win_1',
    category: 'Winnings',
    description: 'Winnings from Lotteries, Crossword Puzzles, or Card Games',
    reference: '393(1) [Sl. No. 10]',
    rate: 30,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_win_2',
    category: 'Winnings',
    description: 'Winnings from Horse Races',
    reference: '393(1) [Sl. No. 10]',
    rate: 30,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_win_online',
    category: 'Winnings',
    description: 'Winnings from Online Games (Net Winnings)',
    reference: '393(1) [Sl. No. 11]',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    specialNote: 'Deducted on net winnings at the time of withdrawal or end of financial year.',
    payerType: 'all',
    payeeType: 'resident',
  },
  // ===================================
  // 5. INTEREST
  // ===================================
  {
    id: 'r_5_i',
    category: 'Interest',
    description: 'Interest on securities',
    reference: '393(1) [Sl. No. 5(i)]',
    rate: 10,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_5_ii_s',
    category: 'Interest',
    description: 'Interest from Bank/Co-op/Post Office (Senior Citizen)',
    reference: '393(1) [Sl. No. 5(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_5_ii_o',
    category: 'Interest',
    description: 'Interest from Bank/Co-op/Post Office (Others)',
    reference: '393(1) [Sl. No. 5(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 40000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_5_iii',
    category: 'Interest',
    description: 'Interest other than on securities (by Specified Person)',
    reference: '393(1) [Sl. No. 5(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 5000,
    payerType: 'specified',
    payeeType: 'resident',
  },
  // ===================================
  // 6. CONTRACTS & PROF SERVICES
  // ===================================
  {
    id: 'r_6_i_ind',
    category: 'Contractors',
    description: 'Contract payment to Individual/HUF',
    reference: '393(1) [Sl. No. 6(i)]',
    rate: 1,
    rateUnit: '%',
    threshold: 30000,
    thresholdNote: 'for single payment, or 1,00,000 aggregate',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_i_oth',
    category: 'Contractors',
    description: 'Contract payment to Others (Companies/Firms)',
    reference: '393(1) [Sl. No. 6(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 30000,
    thresholdNote: 'for single payment, or 1,00,000 aggregate',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_ii_prof',
    category: 'Professional Services',
    description: 'Professional Fees (by Individual/HUF not liable for audit)',
    reference: '393(1) [Sl. No. 6(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 5000000,
    payerType: 'non-specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_iii_tech',
    category: 'Technical Services',
    description: 'Fees for Technical Services',
    reference: '393(1) [Sl. No. 6(iii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 30000,
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_iii_prof',
    category: 'Professional Services',
    description: 'Fees for Professional Services',
    reference: '393(1) [Sl. No. 6(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 30000,
    payerType: 'specified',
    payeeType: 'resident',
  },
  // ===================================
  // 7. OTHER PAYMENTS
  // ===================================
  {
    id: 'r_7_div',
    category: 'Dividend',
    description: 'Dividend payment',
    reference: '393(1) [Sl. No. 7]',
    rate: 10,
    rateUnit: '%',
    threshold: 5000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_8_i_li',
    category: 'Life Insurance',
    description: 'Payment from Life Insurance Policy (Income part)',
    reference: '393(1) [Sl. No. 8(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 100000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_8_ii_goods',
    category: 'Purchase of Goods',
    description: 'Purchase of goods exceeding ₹50 Lakh',
    reference: '393(1) [Sl. No. 8(ii)]',
    rate: 0.1,
    rateUnit: '%',
    threshold: 5000000,
    specialNote: 'Deducted on amount exceeding ₹50,00,000.',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_8_v_ecom',
    category: 'E-commerce',
    description: 'Payment to E-commerce participant',
    reference: '393(1) [Sl. No. 8(v)]',
    rate: 0.1,
    rateUnit: '%',
    threshold: 0,
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_vda',
    category: 'Digital Assets',
    description: 'Transfer of Virtual Digital Asset (VDA)',
    reference: '393(1) [Sl. No. 8(vi)]',
    rate: 1,
    rateUnit: '%',
    threshold: 10000,
    thresholdNote: '50,000 for specified persons',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_cash',
    category: 'Cash Withdrawal',
    description: 'Cash withdrawal exceeding ₹1 Crore',
    reference: '393(1) [Sl. No. 12]',
    rate: 2,
    rateUnit: '%',
    threshold: 10000000,
    specialNote: 'Rate is 2% above ₹20L for non-filers, and 5% above ₹1Cr for non-filers.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_nss',
    category: 'NSS',
    description: 'Payment from National Savings Scheme (NSS)',
    reference: '393(1) [Sl. No. 13]',
    rate: 10,
    rateUnit: '%',
    threshold: 2500,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_mf_rep',
    category: 'Mutual Fund',
    description: 'Repurchase of units by Mutual Fund or UTI',
    reference: '393(1) [Sl. No. 14]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  // ===================================
  // NON-RESIDENT PAYMENTS
  // ===================================
  {
    id: 'nr_win',
    category: 'Non-Resident Winnings',
    description: 'Winnings from Lottery/Online Games (Non-Resident)',
    reference: '393(2) [Sl. No. 1]',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_sports',
    category: 'Non-Resident Sports',
    description: 'Income to Non-resident Sportsman or Entertainer',
    reference: '393(2) [Sl. No. 2]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_int_fc',
    category: 'Non-Resident Interest',
    description: 'Interest on foreign currency loans/bonds',
    reference: '393(2) [Sl. No. 3]',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_int_ifsc',
    category: 'Non-Resident Interest',
    description: 'Interest on bonds listed on IFSC stock exchange',
    reference: '393(2) [Sl. No. 4]',
    rate: 9,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_div',
    category: 'Non-Resident Dividend',
    description: 'Dividend to Non-Resident/Foreign Company',
    reference: '393(2) [Sl. No. 5]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_roy',
    category: 'Non-Resident Royalty',
    description: 'Royalty or Fees for Technical Services (NR)',
    reference: '393(2) [Sl. No. 6]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_ltcg',
    category: 'Non-Resident LTCG',
    description: 'Long Term Capital Gains (Sec 204)',
    reference: '393(2) [Sl. No. 7]',
    rate: 12.5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
];
