import { TdsRule } from './types';

export const TDS_RULES: TdsRule[] = [
  // ===================================
  // RESIDENT PAYEES (Section 393/Legacy)
  // ===================================
  {
    id: 'r_192_salary',
    category: 'Salary',
    description: 'Payment of Salary (Legacy 192)',
    reference: 'Sec 192',
    rate: 0,
    rateUnit: '%',
    threshold: 0,
    thresholdNote: 'Basic Exemption Slabs',
    specialNote: 'Deducted as per income tax slab rates.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_192A_epf',
    category: 'EPF',
    description: 'Premature withdrawal from EPF (Legacy 192A)',
    reference: 'Sec 192A',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_193_securities',
    category: 'Interest',
    description: 'Interest on Securities (Legacy 193)',
    reference: 'Sec 193',
    rate: 10,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194_dividend',
    category: 'Dividend',
    description: 'Dividends (Legacy 194)',
    reference: 'Sec 194',
    rate: 10,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194A_bank',
    category: 'Interest',
    description: 'Interest on bank/post office deposits (Legacy 194A)',
    reference: 'Sec 194A',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194A_bank_senior',
    category: 'Interest',
    description: 'Interest on bank/post office (Senior Citizen) (Legacy 194A)',
    reference: 'Sec 194A',
    rate: 10,
    rateUnit: '%',
    threshold: 100000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194A_others',
    category: 'Interest',
    description: 'Interest (Others) (Legacy 194A)',
    reference: 'Sec 194A',
    rate: 10,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194K_mf',
    category: 'Dividend',
    description: 'Dividend by Mutual Funds (Legacy 194K)',
    reference: 'Sec 194K',
    rate: 10,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194B_lottery',
    category: 'Winnings',
    description: 'Lottery, game shows, gambling winnings (Legacy 194B)',
    reference: 'Sec 194B',
    rate: 30,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194BA_online',
    category: 'Winnings',
    description: 'Online gaming winnings (Legacy 194BA)',
    reference: 'Sec 194BA',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194BB_horse',
    category: 'Winnings',
    description: 'Winnings from horse races (Legacy 194BB)',
    reference: 'Sec 194BB',
    rate: 30,
    rateUnit: '%',
    threshold: 10000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194C_contractor_ind',
    category: 'Contractors',
    description: 'Payment to contractors (Individual/HUF) (Legacy 194C)',
    reference: 'Sec 194C',
    rate: 1,
    rateUnit: '%',
    threshold: 30000,
    thresholdNote: 'or 1,00,000 aggregate',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194C_contractor_oth',
    category: 'Contractors',
    description: 'Payment to contractors (Others) (Legacy 194C)',
    reference: 'Sec 194C',
    rate: 2,
    rateUnit: '%',
    threshold: 30000,
    thresholdNote: 'or 1,00,000 aggregate',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194D_insurance',
    category: 'Commission',
    description: 'Insurance Commission (Legacy 194D)',
    reference: 'Sec 194D',
    rate: 2,
    rateUnit: '%',
    threshold: 20000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194DA_life_policy',
    category: 'Life Insurance',
    description: 'Payment received – Life insurance Policy (Legacy 194DA)',
    reference: 'Sec 194DA',
    rate: 2,
    rateUnit: '%',
    threshold: 100000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194EE_nss',
    category: 'NSS',
    description: 'Payment received – NSS (Legacy 194EE)',
    reference: 'Sec 194EE',
    rate: 10,
    rateUnit: '%',
    threshold: 2500,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194G_lottery_comm',
    category: 'Commission',
    description: 'Lottery Commission (Legacy 194G)',
    reference: 'Sec 194G',
    rate: 2,
    rateUnit: '%',
    threshold: 20000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194H_brokerage',
    category: 'Commission',
    description: 'Commission/Brokerage (Legacy 194H)',
    reference: 'Sec 194H',
    rate: 2,
    rateUnit: '%',
    threshold: 20000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194Ja_tech',
    category: 'Professional Services',
    description: 'Fees – Technical, Call Centre, Royalty, Cine Films (Legacy 194Ja)',
    reference: 'Sec 194J(a)',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194Jb_prof',
    category: 'Professional Services',
    description: 'Fees – All other Professional Services (Legacy 194Jb)',
    reference: 'Sec 194J(b)',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194Ia_machinery',
    category: 'Rent',
    description: 'Rent for Plant & Machinery (Legacy 194I)',
    reference: 'Sec 194I(a)',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194Ib_land',
    category: 'Rent',
    description: 'Rent for Land, Building & Furniture (Legacy 194I)',
    reference: 'Sec 194I(b)',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194IA_property',
    category: 'Immovable Property',
    description: 'Transfer of immovable property (Legacy 194IA)',
    reference: 'Sec 194IA',
    rate: 1,
    rateUnit: '%',
    threshold: 5000000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194IB_rent_ind',
    category: 'Rent',
    description: 'Rent payment by individual / HUF u/s 194IB',
    reference: 'Sec 194IB',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194LA_compulsory',
    category: 'Immovable Property',
    description: 'Compensation on compulsory acquisition (Legacy 194LA)',
    reference: 'Sec 194LA',
    rate: 10,
    rateUnit: '%',
    threshold: 500000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194M_ind_huf',
    category: 'Professional Services',
    description: 'Contracts, Brokerage or Prof Fees by Ind/HUF (Legacy 194M)',
    reference: 'Sec 194M',
    rate: 2,
    rateUnit: '%',
    threshold: 5000000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194N_cash',
    category: 'Cash Withdrawal',
    description: 'Cash withdrawal in excess of 1 crore (Legacy 194N)',
    reference: 'Sec 194N',
    rate: 2,
    rateUnit: '%',
    threshold: 10000000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194O_ecom',
    category: 'E-commerce',
    description: 'TDS on e-commerce participants (Legacy 194O)',
    reference: 'Sec 194O',
    rate: 0.10,
    rateUnit: '%',
    threshold: 500000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194Q_goods',
    category: 'Purchase of Goods',
    description: 'TDS on Purchase of Goods exceeding Rs. 50 Lakh (Legacy 194Q)',
    reference: 'Sec 194Q',
    rate: 0.10,
    rateUnit: '%',
    threshold: 5000000,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_194T_partner',
    category: 'Partnership',
    description: 'Payments by Partnership Firms to Partners (Legacy 194T)',
    reference: 'Sec 194T',
    rate: 10,
    rateUnit: '%',
    threshold: 20000,
    payerType: 'all',
    payeeType: 'resident',
  },

  // ===================================
  // NON-RESIDENT PAYEES (From Images)
  // ===================================
  {
    id: 'nr_194E_sports',
    category: 'Non-Resident',
    description: 'Payment to non-resident sportsmen/sports association',
    reference: 'Sec 194E',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194N_cash',
    category: 'Cash Withdrawal',
    description: 'Cash withdrawal in excess of 1 crore (Legacy 194N)',
    reference: 'Sec 194N',
    rate: 2,
    rateUnit: '%',
    threshold: 10000000,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LB_infra',
    category: 'Non-Resident',
    description: 'Interest on infrastructure debt fund',
    reference: 'Sec 194LB',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LBA_trust_a',
    category: 'Non-Resident',
    description: 'Business trust income (Sec 10(23FC)(a))',
    reference: 'Sec 194LBA(2)',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LBA_trust_b',
    category: 'Non-Resident',
    description: 'Business trust income (Sec 10(23FC)(b))',
    reference: 'Sec 194LBA(2)',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LBA_trust_3',
    category: 'Non-Resident',
    description: 'Business trust income (Sec 10(23FCA))',
    reference: 'Sec 194LBA(3)',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LBB_fund',
    category: 'Non-Resident',
    description: 'Investment fund paying income to unit holder',
    reference: 'Sec 194LBB',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LBC_securitization',
    category: 'Non-Resident',
    description: 'Investment in securitization trust',
    reference: 'Sec 194LBC',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LC_ifsc',
    category: 'Non-Resident',
    description: 'IFSC listed long term bond interest',
    reference: 'Sec 194LC',
    rate: 4,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LC_bond_2023',
    category: 'Non-Resident',
    description: 'Bonds specified after 01-04-2023',
    reference: 'Sec 194LC',
    rate: 9,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_194LD_rupee_bond',
    category: 'Non-Resident',
    description: 'Interest on Rupee Bond (FII/QFI)',
    reference: 'Sec 194LD',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },

  // SECTION 195 ITEMS
  {
    id: 'nr_195_a_inv',
    category: 'Non-Resident (Sec 195)',
    description: 'Investment income by NRI (Sec 115E)',
    reference: 'Sec 195(a)',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_b_ltcg',
    category: 'Non-Resident (Sec 195)',
    description: 'LTCG referred in 115E (NRI)',
    reference: 'Sec 195(b)',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_c_ltcg_112',
    category: 'Non-Resident (Sec 195)',
    description: 'LTCG referred in Sec 112',
    reference: 'Sec 195(c)',
    rate: 12.50,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_d_ltcg_112a',
    category: 'Non-Resident (Sec 195)',
    description: 'LTCG referred in Sec 112A (Above 1.25L)',
    reference: 'Sec 195(d)',
    rate: 12.50,
    rateUnit: '%',
    threshold: 125000,
    specialNote: 'Deducted on amount exceeding 1.25 Lakhs.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_e_stcg_111a',
    category: 'Non-Resident (Sec 195)',
    description: 'STCG referred in Sec 111A',
    reference: 'Sec 195(e)',
    rate: 12.50,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_f_other_ltcg',
    category: 'Non-Resident (Sec 195)',
    description: 'Other LTCG (not 10(33), 10(36))',
    reference: 'Sec 195(f)',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_g_div_ifsc',
    category: 'Non-Resident (Sec 195)',
    description: 'Dividend from unit in IFSC',
    reference: 'Sec 195(g)',
    rate: 12.50,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_h_div_other',
    category: 'Non-Resident (Sec 195)',
    description: 'Dividend income (Other than IFSC)',
    reference: 'Sec 195(h)',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_i_interest',
    category: 'Non-Resident (Sec 195)',
    description: 'Interest on foreign-currency borrowings',
    reference: 'Sec 195(i)',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_j_royalty',
    category: 'Non-Resident (Sec 195)',
    description: 'Royalty / FTS u/s 115A',
    reference: 'Sec 195(j)',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_195_m_other',
    category: 'Non-Resident (Sec 195)',
    description: 'Any other income to Non-Resident',
    reference: 'Sec 195(m)',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },

  // SECTIONS 196A-D
  {
    id: 'nr_196A_units',
    category: 'Non-Resident',
    description: 'Income in respect of units of non-resident',
    reference: 'Sec 196A',
    rate: 30,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_196B_units_115ab',
    category: 'Non-Resident',
    description: 'Income from units (Sec 115AB)',
    reference: 'Sec 196B',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_196C_bonds_int',
    category: 'Non-Resident',
    description: 'Interest/Dividend bonds/GDR (Sec 115AC)',
    reference: 'Sec 196C',
    rate: 12.50,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_196C_bonds_ltcg',
    category: 'Non-Resident',
    description: 'LTCG from transfer of bonds/GDR (Sec 115AC)',
    reference: 'Sec 196C',
    rate: 12.50,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_196D_fii',
    category: 'Non-Resident',
    description: 'Income of FII from securities',
    reference: 'Sec 196D',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_196D_1a',
    category: 'Non-Resident',
    description: 'Income in respect of securities to specified fund',
    reference: 'Sec 196D(1A)',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
];
