import { TdsRule } from './types';

export const TDS_RULES: TdsRule[] = [
  // ===================================
  // Rules for RESIDENT Payees
  // ===================================
  // SL NO 1
  {
    id: 'r_1_i',
    category: 'Commission or Brokerage',
    description: 'Insurance commission',
    reference: '393(1) [Table: Sl. No. 1(i)]',
    rate: 0,
    rateUnit: '%',
    threshold: 20000,
    thresholdNote: 'per financial year',
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_1_ii',
    category: 'Commission or Brokerage',
    description: 'Other commission or brokerage (not insurance)',
    reference: '393(1) [Table: Sl. No. 1(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 20000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  // SL NO 2
  {
    id: 'r_2_i',
    category: 'Rent',
    description: 'Rent (paid by person other than specified person)',
    reference: '393(1) [Table: Sl. No. 2(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per month or part of a month',
    payerType: 'non-specified',
    payeeType: 'resident',
  },
  {
    id: 'r_2_ii_a',
    category: 'Rent',
    description: 'Rent for machinery, plant, or equipment',
    reference: '393(1) [Table: Sl. No. 2(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per month or part of a month',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_2_ii_b',
    category: 'Rent',
    description: 'Rent for land, building, or furniture/fittings',
    reference: '393(1) [Table: Sl. No. 2(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per month or part of a month',
    payerType: 'specified',
    payeeType: 'resident',
  },
  // SL NO 3
  {
    id: 'r_3_i',
    category: 'Immovable Property',
    description: 'Payment on transfer of immovable property (not agricultural land)',
    reference: '393(1) [Table: Sl. No. 3(i)]',
    rate: 1,
    rateUnit: '%',
    threshold: 5000000,
    thresholdNote: 'per transaction',
    specialNote: 'Rate is 1% of consideration or stamp duty value, whichever is higher. This calculator uses the consideration amount.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_3_ii',
    category: 'Immovable Property',
    description: 'Consideration for transfer under specified agreement (Sec 67(14))',
    reference: '393(1) [Table: Sl. No. 3(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_3_iii',
    category: 'Immovable Property',
    description: 'Compensation on compulsory acquisition',
    reference: '393(1) [Table: Sl. No. 3(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 500000,
    payerType: 'all',
    payeeType: 'resident',
  },
  // SL NO 4
  {
    id: 'r_4_i',
    category: 'Capital Market Income',
    description: 'Income from units of Mutual Fund/UTI',
    reference: '393(1) [Table: Sl. No. 4(i)]',
    rate: 10,
    rateUnit: '%',
    threshold: 10000,
    thresholdNote: 'per financial year',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_4_ii',
    category: 'Capital Market Income',
    description: 'Distributed income from Business Trust',
    reference: '393(1) [Table: Sl. No. 4(ii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_4_iii',
    category: 'Capital Market Income',
    description: 'Income from investment fund',
    reference: '393(1) [Table: Sl. No. 4(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_4_iv',
    category: 'Capital Market Income',
    description: 'Income from securitisation trust',
    reference: '393(1) [Table: Sl. No. 4(iv)]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  // SL NO 5
  {
    id: 'r_5_i',
    category: 'Interest',
    description: 'Interest on securities',
    reference: '393(1) [Table: Sl. No. 5(i)]',
    rate: 0,
    rateUnit: '%',
    threshold: 10000,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_5_ii_senior',
    category: 'Interest',
    description: 'Interest from Bank/Co-op/Post Office (Senior Citizen)',
    reference: '393(1) [Table: Sl. No. 5(ii)]',
    rate: 0,
    rateUnit: '%',
    threshold: 100000,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_5_ii_other',
    category: 'Interest',
    description: 'Interest from Bank/Co-op/Post Office (Other than Senior Citizen)',
    reference: '393(1) [Table: Sl. No. 5(ii)]',
    rate: 0,
    rateUnit: '%',
    threshold: 50000,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_5_iii',
    category: 'Interest',
    description: 'Interest other than on securities (by Specified Person)',
    reference: '393(1) [Table: Sl. No. 5(iii)]',
    rate: 0,
    rateUnit: '%',
    threshold: 10000,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payerType: 'specified',
    payeeType: 'resident',
  },
  // SL NO 6
  {
    id: 'r_6_i',
    category: 'Payments to Contractors',
    description: 'Payment to contractor/sub-contractor (Individual/HUF)',
    reference: '393(1) [Table: Sl. No. 6(i)]',
    rate: 1,
    rateUnit: '%',
    threshold: 30000,
    thresholdNote: 'for a single sum, or ₹1,00,000 in aggregate',
    specialNote: 'Tax shall be deducted on (a) the invoice value excluding the value of material, if specified separately in the invoice; or (b) on the whole of the invoice value, if the value of material is not specified separately.',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_i_other',
    category: 'Payments to Contractors',
    description: 'Payment to contractor/sub-contractor (Other than Individual/HUF)',
    reference: '393(1) [Table: Sl. No. 6(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 30000,
    thresholdNote: 'for a single sum, or ₹1,00,000 in aggregate',
    specialNote: 'Tax shall be deducted on (a) the invoice value excluding the value of material, if specified separately in the invoice; or (b) on the whole of the invoice value, if the value of material is not specified separately.',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_ii',
    category: 'Professional or Technical Services',
    description: 'Fees for professional/technical services, etc. (by Individual/HUF not liable for audit)',
    reference: '393(1) [Table: Sl. No. 6(ii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 5000000,
    thresholdNote: 'per financial year',
    payerType: 'non-specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_iii_a',
    category: 'Professional or Technical Services',
    description: 'Fees for technical services (not professional)',
    reference: '393(1) [Table: Sl. No. 6(iii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_iii_b',
    category: 'Professional or Technical Services',
    description: 'Royalty (cinematographic films)',
    reference: '393(1) [Table: Sl. No. 6(iii)]',
    rate: 2,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_iii_c',
    category: 'Professional or Technical Services',
    description: 'Fees for professional services',
    reference: '393(1) [Table: Sl. No. 6(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_6_iii_d',
    category: 'Professional or Technical Services',
    description: 'Royalty (other), director fees/commission, or other contract sums',
    reference: '393(1) [Table: Sl. No. 6(iii)]',
    rate: 10,
    rateUnit: '%',
    threshold: 50000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  // SL NO 7
  {
    id: 'r_7',
    category: 'Dividend',
    description: 'Dividend',
    reference: '393(1) [Table: Sl. No. 7]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payerType: 'all',
    payeeType: 'resident',
  },
  // SL NO 8
  {
    id: 'r_8_i',
    category: 'Other Payments',
    description: 'Payment from life insurance policy',
    reference: '393(1) [Table: Sl. No. 8(i)]',
    rate: 2,
    rateUnit: '%',
    threshold: 100000,
    thresholdNote: 'per financial year',
    specialNote: 'TDS is 2% on the income component of the payment.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_8_ii',
    category: 'Other Payments',
    description: 'Purchase of goods',
    reference: '393(1) [Table: Sl. No. 8(ii)]',
    rate: 0.1,
    rateUnit: '%',
    threshold: 5000000,
    thresholdNote: 'per financial year',
    specialNote: 'TDS is on the amount exceeding ₹50 lakh. This rule does not apply if tax is deductible/collectible under another provision.',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_8_iii',
    category: 'Other Payments',
    description: 'Payment to specified senior citizen by bank',
    reference: '393(1) [Table: Sl. No. 8(iii)]',
    rate: 0,
    rateUnit: '%',
    threshold: 0,
    isComplex: true,
    specialNote: 'TDS is deducted at "Rates in force" on the total income after allowing deductions and rebates. This is a complex calculation not performed by this tool.',
    payerType: 'all',
    payeeType: 'resident',
  },
  {
    id: 'r_8_iv',
    category: 'Other Payments',
    description: 'Benefit or perquisite from business/profession',
    reference: '393(1) [Table: Sl. No. 8(iv)]',
    rate: 10,
    rateUnit: '%',
    threshold: 20000,
    thresholdNote: 'per financial year',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_8_v',
    category: 'E-commerce',
    description: 'Payment to e-commerce participant',
    reference: '393(1) [Table: Sl. No. 8(v)]',
    rate: 0.1,
    rateUnit: '%',
    threshold: 0,
    specialNote: 'Rate is 0.1% of gross amount of sale/services. Threshold is Nil.',
    payerType: 'specified',
    payeeType: 'resident',
  },
  {
    id: 'r_8_vi',
    category: 'Virtual Digital Asset',
    description: 'Payment on transfer of virtual digital asset',
    reference: '393(1) [Table: Sl. No. 8(vi)]',
    rate: 1,
    rateUnit: '%',
    threshold: 0,
    specialNote: 'Threshold is Nil.',
    payerType: 'all',
    payeeType: 'resident',
  },
  // ===================================
  // Rules for NON-RESIDENT Payees
  // ===================================
  {
    id: 'nr_1',
    category: 'Payments to Non-Residents',
    description: 'Income to non-resident sportsman/entertainer (Sec 211)',
    reference: '393(2) [Table: Sl. No. 1]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_2',
    category: 'Payments to Non-Residents',
    description: 'Interest on specific foreign currency loans/bonds (before 1st July 2023)',
    reference: '393(2) [Table: Sl. No. 2]',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_3',
    category: 'Payments to Non-Residents',
    description: 'Interest on rupee denominated bond (before 1st July 2023)',
    reference: '393(2) [Table: Sl. No. 3]',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_4',
    category: 'Payments to Non-Residents',
    description: 'Interest on specific bonds listed on IFSC',
    reference: '393(2) [Table: Sl. No. 4]',
    rate: 0, // Complex
    rateUnit: '%',
    threshold: 0,
    isComplex: true,
    specialNote: 'Rate is 4% for bonds issued between 1st Apr 2020 and 1st July 2023, and 9% for bonds issued after 1st July 2023. Please consult the Act.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_5',
    category: 'Payments to Non-Residents',
    description: 'Interest from Infrastructure Debt Fund',
    reference: '393(2) [Table: Sl. No. 5]',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_6a',
    category: 'Payments to Non-Residents',
    description: 'Distributed income from Business Trust (Interest - Sch V, Sl No 3a)',
    reference: '393(2) [Table: Sl. No. 6]',
    rate: 5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_6b',
    category: 'Payments to Non-Residents',
    description: 'Distributed income from Business Trust (Dividend - Sch V, Sl No 3b)',
    reference: '393(2) [Table: Sl. No. 6]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_7',
    category: 'Payments to Non-Residents',
    description: 'Distributed income from Business Trust (Sch V, Sl No 4)',
    reference: '393(2) [Table: Sl. No. 7]',
    rate: 0,
    rateUnit: '%',
    threshold: 0,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_8',
    category: 'Payments to Non-Residents',
    description: 'Income from Investment Fund units',
    reference: '393(2) [Table: Sl. No. 8]',
    rate: 0,
    rateUnit: '%',
    threshold: 0,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_9',
    category: 'Payments to Non-Residents',
    description: 'Income from Securitisation Trust',
    reference: '393(2) [Table: Sl. No. 9]',
    rate: 0,
    rateUnit: '%',
    threshold: 0,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_10',
    category: 'Payments to Non-Residents',
    description: 'Income from Mutual Fund/UTI units',
    reference: '393(2) [Table: Sl. No. 10]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    specialNote: 'Rate is 20% or as per tax treaty, whichever is lower.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_11',
    category: 'Payments to Non-Residents',
    description: 'Income from Offshore Fund units',
    reference: '393(2) [Table: Sl. No. 11]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_12',
    category: 'Payments to Non-Residents',
    description: 'LTCG from Offshore Fund units',
    reference: '393(2) [Table: Sl. No. 12]',
    rate: 12.5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_13',
    category: 'Payments to Non-Residents',
    description: 'Interest/Dividends on bonds or GDRs (Sec 209)',
    reference: '393(2) [Table: Sl. No. 13]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_14',
    category: 'Payments to Non-Residents',
    description: 'LTCG from bonds or GDRs (Sec 209)',
    reference: '393(2) [Table: Sl. No. 14]',
    rate: 12.5,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_15',
    category: 'Payments to Non-Residents',
    description: 'Income from securities (Foreign Institutional Investor)',
    reference: '393(2) [Table: Sl. No. 15]',
    rate: 20,
    rateUnit: '%',
    threshold: 0,
    specialNote: 'Rate is 20% or as per tax treaty, whichever is lower.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_16',
    category: 'Payments to Non-Residents',
    description: 'Income from securities (Specified Fund)',
    reference: '393(2) [Table: Sl. No. 16]',
    rate: 10,
    rateUnit: '%',
    threshold: 0,
    payeeType: 'non-resident',
    payerType: 'all',
  },
  {
    id: 'nr_17',
    category: 'Payments to Non-Residents',
    description: 'Other interest or any other sum chargeable (not salary)',
    reference: '393(2) [Table: Sl. No. 17]',
    rate: 0,
    rateUnit: '%',
    threshold: 0,
    isComplex: true,
    specialNote: 'Tax is deducted at "Rates in force". This calculator does not compute this. Please consult the current Finance Act and/or any applicable tax treaty.',
    payeeType: 'non-resident',
    payerType: 'all',
  },
];
